### ISSUE TITLE
encapsulate as money fails in when you try to set an integer/float as the value

### ISSUE THREAD

**Issue by asellitt** [envato/encapsulate_as_money#1]
this line: https://github.com/envato/encapsulate_as_money/blob/master/lib/encapsulate_as_money.rb#L30 fails if you dont pass a money object into the setter.

using these two facts:
- `Money.new(Money.new(100_00)) == Money.new(100_00)`
- `Money.new(nil) == Money.new(0)`

we can do:

``` ruby
super(Money.new(amount).fractional)
```

...maybe...

**Comment by orien** [comment]
Isn't the whole point of `encapsulate_as_money` to pass in a `Money` instance to the writer and receive a `Money` instance from the reader?

**Comment by asellitt** [comment]
oos
